version = 1

# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

[[annotations]]
path = [
     "*.lock",
     "*.log",
     "*.coverage",
     "*.buildinfo*",
     "test_coverage_report*",
     "LICENSES/*",
     ".uvignore",
     ".python-version",
]
SPDX-License-Identifier = "Apache-2.0"
SPDX-FileCopyrightText = "2025 The Linux Foundation"
